// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODExplorer.Database;

#nullable disable

namespace ODExplorer.Migrations
{
    [DbContext(typeof(ODExplorerDbContext))]
    [Migration("20241130171721_EdAstroPois")]
    partial class EdAstroPois
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CommanderIgnoredSystems", b =>
                {
                    b.Property<long>("CartoIgnoredSystemsDTOAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartoIgnoredSystemsDTOAddress", "CommandersId");

                    b.HasIndex("CommandersId");

                    b.ToTable("CommanderIgnoredSystems");
                });

            modelBuilder.Entity("ODExplorer.Database.DTOs.CartoIgnoredSystemsDTO", b =>
                {
                    b.Property<long>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.HasIndex("Address");

                    b.ToTable("CartoIgnoredSystems");
                });

            modelBuilder.Entity("ODExplorer.Database.DTOs.EdAstroPoiDTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceFromSol")
                        .HasColumnType("REAL");

                    b.Property<string>("GalMapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type2")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EdAstroPois");
                });

            modelBuilder.Entity("ODUtils.Database.DTOs.JournalCommanderDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JournalDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JournalCommanders");
                });

            modelBuilder.Entity("ODUtils.Database.DTOs.JournalEntryDTO", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommanderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Filename", "Offset");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("TimeStamp", "Offset");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ODUtils.Database.DTOs.SettingsDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("CommanderIgnoredSystems", b =>
                {
                    b.HasOne("ODExplorer.Database.DTOs.CartoIgnoredSystemsDTO", null)
                        .WithMany()
                        .HasForeignKey("CartoIgnoredSystemsDTOAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ODUtils.Database.DTOs.JournalCommanderDTO", null)
                        .WithMany()
                        .HasForeignKey("CommandersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
